apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fly-frp-tunnel-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fly-frp-tunnel-operator
subjects:
  - kind: ServiceAccount
    name: fly-frp-tunnel-operator
    namespace: fly-frp-tunnel-system
